### ISSUE TITLE
Duplicate key name "compositing-foreground" defined in section "settings"

### ISSUE THREAD

**Issue by EliasTheDev** [nothingButSyntaxError/dotfiles#2] opened 2021-12-31 10:25 UTC
* OS: `Arch Linux`
* WM: `i3`
* Issue: 
`➜  ~ polybar example -c ~/.config/polybar/config.ini
notice: Parsing config file: /home/enigma/.config/polybar/config.ini
error: /home/enigma/.config/polybar/settings.ini:5: Duplicate key name "compositing-foreground" defined in section "settings"`

- Any idea why this error is occuring? Thanks!

**Comment by p4rthh** [comment] 2021-12-31 10:51
Hmm.. Doesnt happen with me. What is your polybar version? Try running `polybar --version` and let me know the output.

**Comment by EliasTheDev** [comment] 2021-12-31 10:58
Yeah sure! I got this output:
```
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by p4rthh** [comment] 2021-12-31 11:19
Okay, so i just tried this on my arch with i3 and it worked without any problems. What i feel is there is some problem with polybar. Like, when you were installing/building it you might have encountered some problems or it seems this could be a problem with your compositor because to use this bar you need picom with glx backend so just check if you are running any compositor in the background like picom or any other. I REALLY FEEL THIS IS A PROBLEM WITH THE COMPOSITOR SO DO WHAT I SAID ABOVE AND LEMME KNOW. thanks

**Comment by EliasTheDev** [comment] 2021-12-31 11:26
Appearently, it was the compositor - picom - who was causing the main issue. But sadly, we have another issue:

```
notice: Parsing config file: /home/enigma/.config/polybar/config.ini
error: Undefined bar: example
```

**Comment by p4rthh** [comment] 2021-12-31 11:32
Umm no. This is not exactly an issue here but you are doing it wrong. Instead of running polybar this way run it from the launcher.bash script provided so `./launcher.bash`

**Comment by EliasTheDev** [comment] 2021-12-31 11:35
Yup! this worked perfectly fine. Thanks for your time!

**Comment by p4rthh** [comment] 2021-12-31 11:42
Gald to know. Would you like to share a screenshot of how it is looking on your setup. Just curious and i like to see the result after helping someone out.

**Comment by EliasTheDev** [comment] 2021-12-31 11:58
I'm not gonna say it's awful. But unsatisfying, probably because I didn't install material design font on my machine

![Here it is](https://user-images.githubusercontent.com/95052783/147822162-fa69e4bc-e1b7-4054-9654-15a833e72f88.png)

**Comment by p4rthh** [comment] 2021-12-31 12:00
Hmm looks like you are missing a font or 2. Alright then. Looks good. I am gonna close the issue since the problem is solved.

**Closed as completed by p4rthh** 2021-12-31 12:00 UTC
Labels: bug
